AdopteDevWebApp/Controllers/LoginController.cs
using AdopteDevWebApp.Interface;
using AdopteDevWebApp.Models.User;
using AdopteDevWebApp.Security;
using AdopteDevWebApp.Tools;
using DataAccess.Entities;
using DataAccess.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AdopteDevWebApp.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILoginService _logService;
        private readonly IHashPw _hashService;

        public LoginController(ILoginService logService, IHashPw hashService)
        {
            _logService = logService;
            _hashService = hashService;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login([FromForm] LoginModel logForm)
        {
            if (!ModelState.IsValid)
            {
                return View(logForm);
            }

            GetUserModel currentUser = _logService.Login(logForm.Email, logForm.Password).UserToWebApp();
            // il faut utiliser le HttpContext.Session pour écrire en Session
            HttpContext.Session.SetUser(currentUser);

            //if (uLog == null || uLog.Password != _hashService.HashPassword(logForm.Password))
            //{
            //    TempData["error"] = "Connection problem!";
            //    return View(logForm);
            //}
            // if(client.Password == password) rediriger
            TempData["success"] = "Welcome " + currentUser.Email;
            //HttpContext.Session.SetString("Rôle", user.IsClient ? "Client" : "Developper");
            //HttpContext.Session.SetInt32("Id", user.Id);

            return RedirectToAction("Index", "Home");
        }
    }
}

AdopteDevWebApp/Controllers/UserController.cs
using AdopteDevWebApp.Interface;
using AdopteDevWebApp.Models.User;
using AdopteDevWebApp.Tools;
using DataAccess.Entities;
using DataAccess.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AdopteDevWebApp.Controllers
{
    public class UserController : Controller
    {
        private readonly IService<User> _userService;

        public UserController(IService<User> userService)
        {
            _userService = userService;
        }

        [AuthorizationRequired]
        public IActionResult Index()
        {
            return View(_userService.GetAll(HttpContext.Session.GetUser().Token).Select(u => u.UserToWebApp()));
        }
        [AuthorizationRequired]
        [DevRequired]
        public IActionResult Delete(int id)
        {
            _userService.Delete(id, HttpContext.Session.GetUser().Token);
            TempData["success"] = "Deleted with success! ";
            return RedirectToAction("Index");
        }

        [AuthorizationRequired]
        public IActionResult Logout()
        {
            HttpContext.Session.Disconnect();
            return RedirectToAction("index");
        }
    }
}

AdopteDevWebApp/Views/Shared/_Layout.cshtml
@using AdopteDevWebApp.Tools;
@*@model AdopteDevWebApp.Models.User.GetUserModel;*@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdopteDevWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AdopteDevWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-column-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        @if (SessionManager.userModel == null)
                        {
                            <li class="nav-item" style="text-align: right;">
                                <a class="btn btn-success" asp-area="" asp-controller="Login" asp-action="Login">Sign in</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item" style="text-align: right;">
                                <a class="btn btn-danger" asp-area="" asp-controller="User" asp-action="Logout">Sign out</a>
                                @if (SessionManager.userModel != null && SessionManager.userModel.IsClient)
                                    {
                                        <span style="color: red; font-weight: 500; opacity: 0.5;">@SessionManager.userModel.Name / #Client</span>
                                    }
                                    else
                                    {
                            <span style="color: red; font-weight: 500; opacity: 0.5;">@SessionManager.userModel.Name / #Developper</span>
                                    }
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AdopteDevWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @if (TempData["success"] != null)
    {
        <script>
            toastr.success('@TempData["Success"]');
        </script>
    }
</body>
</html>